name: 'Multi-state Terraform Plan Staging'
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'multi-state-demo/environments/staging/**'
env:
  TF_ACTIONS_VERSION: 0.12.28
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_ACTIONS_VERSION }}
      - name: Terraform Format
        id: fmt
        working-directory: multi-state-demo/environments/staging
        run: terraform fmt -recursive
        continue-on-error: true
      - name: Terraform Init
        id: init
        working-directory: multi-state-demo/environments/staging
        run: |
          terraform init
      - name: Terraform Validate
        id: validate
        working-directory: multi-state-demo/environments/staging
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        working-directory: multi-state-demo/environments/staging
        run: |
          terraform plan -no-color
        continue-on-error: true
      - uses: actions/github-script@0.9.0
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          ERROR: "${{ steps.plan.outputs.stderr }}"
          VALIDATE: "${{ steps.validate.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const formatted_plan = process.env.PLAN.replace(/`/g,'\`')
            const formatted_validate = process.env.VALIDATE.replace(/`/g,'\`')
            const formatted_error = process.env.ERROR.replace(/`/g,'\`')
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖 ${formatted_validate}
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\` ${formatted_plan} ${formatted_error}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`demo\`, Workflow: \`${{ github.workflow }}\`*
            *run : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
